/**
 * Generated API types for the backend's OpenAPI surface.
 *
 * `schema.ts` is generated by `pnpm gen` (openapi-typescript) from adh's
 * `frontend/src/main/api/openapi.json` — which is NOT in this repo, so the spec
 * path is an explicit input (`ADH_OPENAPI_SPEC`), never derived. Do not edit
 * `schema.ts` by hand; regenerate after any backend route/schema change,
 * alongside `pnpm openapi:dump` in adh's `backend/src/adh`. The committed file is
 * what ships, so a consumer without an adh checkout builds fine.
 */
export type { paths, components } from './schema'

import type { paths } from './schema'

/** Unwrap the `application/json` body out of an OpenAPI response object. */
type JsonBody<T> = T extends { content: { 'application/json': infer B } } ? B : never

/**
 * The JSON body of a successful response for an operation, keyed by path +
 * method (status defaults to 200). Examples:
 *   SuccessBody<'/customer/customers', 'get'>          // the 200 list body
 *   SuccessBody<'/customer/customers', 'post', 201>    // the 201 create body
 *
 * A backend schema change regenerates `schema.ts`, so any consumer reading a
 * removed/renamed field stops type-checking — that's the contract guard.
 */
export type SuccessBody<
  P extends keyof paths,
  M extends keyof paths[P],
  Status extends number = 200,
> = paths[P][M] extends { responses: Record<Status, infer R> } ? JsonBody<R> : never

/**
 * The JSON request body for an operation, keyed by path + method. Examples:
 *   RequestBody<'/customer/customers', 'post'>           // the create payload
 *   Partial<RequestBody<'/customer/customers/{id}', 'put'>>  // a partial update
 *
 * Server-managed columns (id, timestamps, owner/tenant scope) are already
 * stripped from the generated create schema. Typing an outgoing payload with
 * this means a backend change to the WRITABLE columns (rename, new required
 * field) stops the `JSON.stringify(body)` call from type-checking — the write
 * side of the contract guard.
 */
export type RequestBody<P extends keyof paths, M extends keyof paths[P]> =
  paths[P][M] extends { requestBody?: infer R } ? JsonBody<NonNullable<R>> : never
