import { defineConfig } from 'tsup'
import { preserveDirectivesPlugin } from 'esbuild-plugin-preserve-directives'

export default defineConfig([
  {
    entry: {
      index: 'src/index.ts',
      ReferenceSite: 'src/ReferenceSite.tsx',
    },
    outDir: 'dist',
    format: ['esm'],
    target: 'es2022',
    platform: 'browser',
    sourcemap: true,
    clean: true,
    dts: false,
    bundle: true,
    splitting: true,
    outExtension: () => ({ js: '.js' }),
    external: [
      'react',
      'react-dom',
      'react/jsx-runtime',
      'react-router',
      '@agentic-toolkit/themes',
      '@agentic-toolkit/themes/colorMode',
      '@agentic-toolkit/controls',
      '@agentic-toolkit/controls/appearance-mode-toggle',
      'shiki',
      'virtual:reference-site-content',
    ],
    esbuildPlugins: [
      preserveDirectivesPlugin({
        directives: ['use client', 'use server'],
        include: /\.(js|ts|jsx|tsx)$/,
        exclude: /node_modules/,
      }),
    ],
  },
  {
    entry: { vite: 'src/vite.ts' },
    outDir: 'dist',
    format: ['esm'],
    target: 'node20',
    platform: 'node',
    sourcemap: true,
    clean: false,
    dts: false,
    bundle: true,
    splitting: false,
    outExtension: () => ({ js: '.js' }),
    external: [
      'vite',
      'gray-matter',
      'unified',
      'remark-parse',
      'remark-gfm',
      'remark-rehype',
      'rehype-slug',
      'rehype-autolink-headings',
      'rehype-stringify',
      'shiki',
      'node:fs',
      'node:path',
      'fs',
      'path',
    ],
  },
])
