packages:
  - './packages/ui'
  - './packages/editing'
  - './packages/themes'
  - './packages/markdown'
  - './packages/search'
  - './packages/model'
  - './packages/controls'
  - './packages/auth'
  - './packages/api-explorer'
  - './packages/crud'
  - './packages/data'
  - './packages/resource'
  - './packages/adh'
  - './packages/persona'
  - './packages/adh-registry'
  - './packages/adh-site-config'
  - './packages/adh-site-homes'
  - './packages/adh-api-types'
  - './packages/adh-ui'
  - './packages/deploy-platform'
  - './packages/next-preflight'
  - './packages/next-headers'
  - './packages/next-env'
  - './packages/adh-next-config'
  - './packages/landing'
  - './packages/messaging'
  - './packages/features/*'
