import Foundation

/// The shared model table: one description per model, however many gateways serve it.
///
/// A model is not a property of the provider that hosts it — `gpt-oss-120b` is the
/// same model at Groq, Fireworks and Cloudflare, and describing it inside each
/// `descriptor.json` would copy one blurb eleven times and let the copies drift.
/// So descriptors list only the model *names* a provider serves, and the shared
/// facts live here once, keyed by a canonical id with every gateway's spelling
/// recorded as an alias.
///
/// The split matters for correctness, not just size: a model's description and
/// capabilities are the same everywhere, but its context window, output limit and
/// token prices are set by whoever serves it (DeepSeek-V4-Pro is 262K tokens at one
/// gateway and 1M at another). Those live per `templateId` in `offerings` so the
/// UI can show the numbers that actually apply, instead of one number that would be
/// wrong nearly everywhere.
///
/// Generated by `AIPlugins/tools/generate_model_catalog.py` from adh's catalog;
/// shipped as a resource of this framework, which the host app embeds and every
/// `.aiplugin` links, so one copy serves all of them.
public struct AIModelCatalog: Codable, Sendable {

    /// One model, independent of who serves it.
    public struct Model: Codable, Sendable, Equatable {
        /// The canonical id — a gateway-neutral name (`llama-3.3-70b-instruct`).
        public let id: String
        /// Every spelling seen in the catalog, e.g. `meta-llama/Llama-3.3-70B-Instruct`
        /// and `@cf/meta/llama-3.3-70b-instruct-fp8-fast`.
        public let aliases: [String]
        public let description: String?
        /// `tools`, `reasoning`, `vision` — what a majority of serving gateways report.
        public let capabilities: [String]

        public init(id: String, aliases: [String] = [], description: String? = nil,
                    capabilities: [String] = []) {
            self.id = id
            self.aliases = aliases
            self.description = description
            self.capabilities = capabilities
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            id = try container.decode(String.self, forKey: .id)
            aliases = try container.decodeIfPresent([String].self, forKey: .aliases) ?? []
            description = try container.decodeIfPresent(String.self, forKey: .description)
            capabilities = try container.decodeIfPresent([String].self, forKey: .capabilities) ?? []
        }
    }

    /// What one provider charges and allows for one model. Absent fields are unknown.
    public struct Offering: Codable, Sendable, Equatable {
        public let contextWindow: Int?
        public let maxOutput: Int?
        public let inputCostPerM: Double?
        public let outputCostPerM: Double?

        public init(contextWindow: Int? = nil, maxOutput: Int? = nil,
                    inputCostPerM: Double? = nil, outputCostPerM: Double? = nil) {
            self.contextWindow = contextWindow
            self.maxOutput = maxOutput
            self.inputCostPerM = inputCostPerM
            self.outputCostPerM = outputCostPerM
        }
    }

    /// Everything known about one model as served by one provider: the shared facts
    /// merged with that provider's numbers and the template's own curated copy.
    public struct ResolvedModel: Sendable, Equatable {
        public let id: String
        public let description: String?
        public let capabilities: [String]
        /// Curated only — the descriptor's `modelDetails` blurb about strengths.
        public let goodFor: String?
        public let tools: Bool?
        public let contextWindow: Int?
        public let maxOutput: Int?
        public let inputCostPerM: Double?
        public let outputCostPerM: Double?

        public var isEmpty: Bool {
            description == nil && capabilities.isEmpty && goodFor == nil && tools == nil
                && contextWindow == nil && maxOutput == nil
                && inputCostPerM == nil && outputCostPerM == nil
        }

        public init(id: String, description: String? = nil, capabilities: [String] = [],
                    goodFor: String? = nil, tools: Bool? = nil,
                    contextWindow: Int? = nil, maxOutput: Int? = nil,
                    inputCostPerM: Double? = nil, outputCostPerM: Double? = nil) {
            self.id = id
            self.description = description
            self.capabilities = capabilities
            self.goodFor = goodFor
            self.tools = tools
            self.contextWindow = contextWindow
            self.maxOutput = maxOutput
            self.inputCostPerM = inputCostPerM
            self.outputCostPerM = outputCostPerM
        }
    }

    public let schemaVersion: Int
    public let generatedAt: String?
    public let models: [Model]
    /// `templateId -> model name as that provider spells it -> its terms`.
    public let offerings: [String: [String: Offering]]

    /// Exact name (any alias or canonical id) -> model, and a second index on the
    /// canonical form so a name the catalog has never seen — a live-fetched local
    /// model, a gateway's new prefix — still resolves.
    private let byName: [String: Model]
    private let byCanonicalID: [String: Model]

    // MARK: - Lookup

    /// The shared facts for a model, by any name a provider might use for it.
    public func model(named name: String) -> Model? {
        byName[name] ?? byName[name.lowercased()] ?? byCanonicalID[Self.canonicalID(name)]
    }

    /// What `templateID` charges and allows for `model`, if the catalog knows.
    public func offering(templateID: String, model: String) -> Offering? {
        offerings[templateID]?[model]
    }

    /// Merge the shared facts, the provider's terms, and the template's curated
    /// copy into what the UI shows for one model of one provider.
    ///
    /// Curated `modelDetails` win: they are hand-written for the few flagship
    /// models where the generated blurb isn't good enough, and a regeneration must
    /// never silently overwrite that judgement.
    public func resolve(
        model name: String, template: AIPluginDescriptor.ProviderTemplate
    ) -> ResolvedModel {
        let curated = template.modelDetail(for: name)
        let shared = model(named: name)
        let terms = offering(templateID: template.id, model: name)
        let capabilities = shared?.capabilities ?? []
        return ResolvedModel(
            id: name,
            description: curated?.description.flatMap { $0.isEmpty ? nil : $0 } ?? shared?.description,
            capabilities: capabilities,
            goodFor: curated?.goodFor,
            tools: curated?.tools ?? (capabilities.isEmpty ? nil : capabilities.contains("tools")),
            contextWindow: terms?.contextWindow,
            maxOutput: terms?.maxOutput,
            inputCostPerM: terms?.inputCostPerM,
            outputCostPerM: terms?.outputCostPerM)
    }

    /// The catalog key for a provider's spelling of a model.
    ///
    /// Mirrors `canonical_model_id` in `generate_model_catalog.py` — that function
    /// builds the alias index this falls back from, so the two must agree. Change
    /// them together.
    public static func canonicalID(_ name: String) -> String {
        var ident = name.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        if let slash = ident.lastIndex(of: "/") { ident = String(ident[ident.index(after: slash)...]) }
        if ident.hasSuffix(":free") { ident = String(ident.dropLast(":free".count)) }
        for suffix in ["-fp8-fast", "-fp8", "-fp4", "-bf16", "-awq", "-int8", "-int4"]
        where ident.hasSuffix(suffix) {
            return String(ident.dropLast(suffix.count))
        }
        return ident
    }

    // MARK: - Loading

    /// The catalog shipped with this framework. Empty (never nil) if the resource is
    /// missing or unreadable — a stale or absent catalog costs descriptions, and must
    /// never take the provider UI down with it.
    public static let shared: AIModelCatalog = load() ?? AIModelCatalog()

    static func load(from bundle: Bundle = Bundle(for: BundleToken.self)) -> AIModelCatalog? {
        guard let url = bundle.url(forResource: "model-catalog", withExtension: "json"),
              let data = try? Data(contentsOf: url) else { return nil }
        return try? JSONDecoder().decode(AIModelCatalog.self, from: data)
    }

    private init() {
        self.init(schemaVersion: 0, generatedAt: nil, models: [], offerings: [:])
    }

    public init(schemaVersion: Int, generatedAt: String?, models: [Model],
                offerings: [String: [String: Offering]]) {
        self.schemaVersion = schemaVersion
        self.generatedAt = generatedAt
        self.models = models
        self.offerings = offerings
        var byName: [String: Model] = [:]
        var byCanonicalID: [String: Model] = [:]
        for model in models {
            byCanonicalID[model.id] = model
            for alias in [model.id] + model.aliases {
                byName[alias] = model
                byName[alias.lowercased()] = model
            }
        }
        self.byName = byName
        self.byCanonicalID = byCanonicalID
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.init(
            schemaVersion: try container.decode(Int.self, forKey: .schemaVersion),
            generatedAt: try container.decodeIfPresent(String.self, forKey: .generatedAt),
            models: try container.decodeIfPresent([Model].self, forKey: .models) ?? [],
            offerings: try container.decodeIfPresent(
                [String: [String: Offering]].self, forKey: .offerings) ?? [:])
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(schemaVersion, forKey: .schemaVersion)
        try container.encodeIfPresent(generatedAt, forKey: .generatedAt)
        try container.encode(models, forKey: .models)
        try container.encode(offerings, forKey: .offerings)
    }

    private enum CodingKeys: String, CodingKey {
        case schemaVersion, generatedAt, models, offerings
    }
}

/// Anchors `Bundle(for:)` on this framework so the catalog resource is found in the
/// host's loaded copy of AIPluginKit, wherever the app bundle lives.
final class BundleToken {}
