import { featureTsup } from '../features/tsup.preset'

// Shares the feature build knowledge (ESM, browser, splitting, directives preserved,
// react/next/@agentic-toolkit external) rather than restating it. The entry MAP is the
// only thing this package adds: one entry per site, so mounting one model never pulls
// the other 46. Generated alongside package.json's exports -- the two must
// name the same 47 sites, which `pnpm lint` in this package proves by resolving them.
export default featureTsup({
  "sites/academy": "src/sites/academy.tsx",
  "sites/authentication": "src/sites/authentication.tsx",
  "sites/billing": "src/sites/billing.tsx",
  "sites/codereviews": "src/sites/codereviews.tsx",
  "sites/communities": "src/sites/communities.tsx",
  "sites/community": "src/sites/community.tsx",
  "sites/consultants": "src/sites/consultants.tsx",
  "sites/consulting": "src/sites/consulting.tsx",
  "sites/cookbook": "src/sites/cookbook.tsx",
  "sites/customers": "src/sites/customers.tsx",
  "sites/dashboards": "src/sites/dashboards.tsx",
  "sites/devices": "src/sites/devices.tsx",
  "sites/devteam": "src/sites/devteam.tsx",
  "sites/docs": "src/sites/docs.tsx",
  "sites/domains": "src/sites/domains.tsx",
  "sites/ecosystems": "src/sites/ecosystems.tsx",
  "sites/education": "src/sites/education.tsx",
  "sites/games": "src/sites/games.tsx",
  "sites/gamification": "src/sites/gamification.tsx",
  "sites/help": "src/sites/help.tsx",
  "sites/integrations": "src/sites/integrations.tsx",
  "sites/knowledgebases": "src/sites/knowledgebases.tsx",
  "sites/messages": "src/sites/messages.tsx",
  "sites/messaging": "src/sites/messaging.tsx",
  "sites/narratives": "src/sites/narratives.tsx",
  "sites/news": "src/sites/news.tsx",
  "sites/notebook": "src/sites/notebook.tsx",
  "sites/notifications": "src/sites/notifications.tsx",
  "sites/orgs": "src/sites/orgs.tsx",
  "sites/personabuilder": "src/sites/personabuilder.tsx",
  "sites/personas": "src/sites/personas.tsx",
  "sites/products": "src/sites/products.tsx",
  "sites/projects": "src/sites/projects.tsx",
  "sites/recipes": "src/sites/recipes.tsx",
  "sites/registries": "src/sites/registries.tsx",
  "sites/registry": "src/sites/registry.tsx",
  "sites/research": "src/sites/research.tsx",
  "sites/sites": "src/sites/sites.tsx",
  "sites/storage": "src/sites/storage.tsx",
  "sites/store": "src/sites/store.tsx",
  "sites/stores": "src/sites/stores.tsx",
  "sites/support": "src/sites/support.tsx",
  "sites/teambuilder": "src/sites/teambuilder.tsx",
  "sites/teamregistry": "src/sites/teamregistry.tsx",
  "sites/testing": "src/sites/testing.tsx",
  "sites/toolkit": "src/sites/toolkit.tsx",
  "sites/tools": "src/sites/tools.tsx"
})
