#!/usr/bin/env python3
"""Generate @agentic-toolkit/api-explorer's src/generated/endpoints.generated.ts.

The dumped spec (frontend/src/sites/api/openapi.json) is the single authoritative
description of every REST endpoint — URL, params, request/response schemas, error
codes, tags, and (via collection + item path pairs) CRUD families. This script
projects it into a compact runtime module the ApiEndpointPanel consumes:

  * API_SCHEMAS   — the spec's components.schemas, verbatim. Stored ONCE; the panel
                    resolves `$ref` against it at render time (with a cycle guard),
                    so shared/recursive schemas don't bloat the file.
  * API_ENDPOINTS — one EndpointMeta per operation, keyed "<METHOD> <path>", with
                    param / body / response schemas kept as `$ref`s where the spec
                    used them (no inlining).

Deterministic output (endpoint keys sorted; inner dict order preserved from the
spec) so reruns are diff-stable; the drift gate (src/__tests__/endpoints.test.ts)
cross-checks the committed module against the spec.

Generic-CRUD operations carry no operationId, so operations are identified by
method+path only — which is exactly the map key.
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path
from typing import Any

PACKAGE_DIR = Path(__file__).resolve().parents[1]
#  This package now lives INSIDE agentictoolkit, so the package it writes into
#  (@agentic-toolkit/api-explorer, which owns the runtime half) is a sibling.
#  No repo-crossing walk any more.
TOOLKIT_PACKAGES = PACKAGE_DIR.parent
OUT_PATH = (
    TOOLKIT_PACKAGES / "api-explorer" / "src" / "generated" / "endpoints.generated.ts"
)


def resolve_spec(argv: list[str] | None = None) -> Path:
    """Locate adh's OpenAPI spec, which is an INPUT — never a computed path.

    The spec belongs to adh. This repo is consumed standalone by repos that have
    no openapi.json at all, so there is no relative location this file could
    honestly derive. It used to derive one (`parents[1].parent.parent` back when
    the package sat at `frontend/src/app/api-types`), and when the package moved
    into the toolkit that walk silently retargeted to a directory that does not
    exist — the same stale-path break this move exposed in four other tools. An
    explicit input either resolves or says why it didn't.
    """
    args = sys.argv[1:] if argv is None else argv
    # pnpm forwards the `--` separator through to the script, so the invocation this
    # file's own generated header documents arrives here as ['--', '<spec>'] and the
    # separator gets read as the path ("spec not found: .../--"). Drop one leading `--`.
    if args and args[0] == "--":
        args = args[1:]
    raw = args[0] if args else os.environ.get("ADH_OPENAPI_SPEC")
    if not raw:
        raise SystemExit(
            "no OpenAPI spec given. This generator reads adh's committed spec, "
            "which does not live in this repo. Pass it as the first argument or "
            "set ADH_OPENAPI_SPEC:\n"
            "  ADH_OPENAPI_SPEC=<adh>/frontend/src/sites/api/openapi.json "
            "python3 tools/gen_endpoints.py"
        )
    spec = Path(raw).expanduser().resolve()
    if not spec.is_file():
        raise SystemExit(f"spec not found: {spec}")
    return spec

# Verbs we project. HEAD/OPTIONS/TRACE carry no try-it value.
METHODS = ("get", "post", "put", "patch", "delete")

# Strip exactly one trailing `/{param}` segment to collapse an item path onto its
# collection base, so `/x/y` and `/x/y/{id}` group together as one CRUD family.
ITEM_TAIL_RE = re.compile(r"/\{[^}]+\}$")

HEADER = """\
// GENERATED by @agentic-toolkit/adh-api-types tools/gen_endpoints.py — do not edit
// by hand. Source: adh's frontend/src/sites/api/openapi.json, which is NOT in this
// repo — the spec is an explicit input, so regenerate with a path to an adh checkout:
//   pnpm --filter @agentic-toolkit/adh-api-types gen:api-endpoints -- <adh>/frontend/src/sites/api/openapi.json
import type { ApiSchemas, EndpointMeta } from '../types'

"""


def resolve_local_ref(spec: dict[str, Any], node: Any) -> Any:
    """One-hop resolve of a `#/...` ref (params / requestBodies / responses live
    in components and may be referenced). Schema `$ref`s are deliberately LEFT in
    place — the panel resolves those against API_SCHEMAS."""
    if isinstance(node, dict) and "$ref" in node and isinstance(node["$ref"], str):
        ref = node["$ref"]
        if ref.startswith("#/"):
            target: Any = spec
            for part in ref[2:].split("/"):
                if not isinstance(target, dict) or part not in target:
                    return node
                target = target[part]
            return target
    return node


def pick_json_content(content: dict[str, Any]) -> tuple[str | None, Any]:
    """Prefer application/json; else the first declared content type."""
    if not isinstance(content, dict) or not content:
        return None, None
    if "application/json" in content:
        return "application/json", content["application/json"].get("schema")
    ctype = next(iter(content))
    entry = content.get(ctype) or {}
    return ctype, entry.get("schema") if isinstance(entry, dict) else None


def security_scheme_names(security: Any) -> list[str]:
    """Flatten OpenAPI `security` ([{scheme: scopes}, ...]) to sorted scheme names."""
    names: set[str] = set()
    if isinstance(security, list):
        for requirement in security:
            if isinstance(requirement, dict):
                names.update(requirement.keys())
    return sorted(names)


def build_params(spec: dict[str, Any], path_item: dict[str, Any], op: dict[str, Any]) -> list[dict[str, Any]]:
    # Path-level first so path params keep their leading position; an op-level entry
    # for the same (name, in) OVERRIDES the path-level one (OpenAPI's rule) while
    # keeping the slot — dict reassignment updates the value but not the position.
    raw = list(path_item.get("parameters", []) or []) + list(op.get("parameters", []) or [])
    merged: dict[tuple[str, str], dict[str, Any]] = {}
    for entry in raw:
        param = resolve_local_ref(spec, entry)
        if not isinstance(param, dict):
            continue
        location = param.get("in")
        name = param.get("name")
        if location not in ("path", "query") or not isinstance(name, str):
            continue
        out: dict[str, Any] = {
            "name": name,
            "in": location,
            # Path params are required by definition; honour explicit `required` otherwise.
            "required": True if location == "path" else bool(param.get("required", False)),
            "schema": param.get("schema", {}) if isinstance(param.get("schema"), dict) else {},
        }
        if isinstance(param.get("description"), str):
            out["description"] = param["description"]
        merged[(name, location)] = out
    return list(merged.values())


def build_request_body(spec: dict[str, Any], op: dict[str, Any]) -> dict[str, Any] | None:
    rb = resolve_local_ref(spec, op.get("requestBody"))
    if not isinstance(rb, dict):
        return None
    ctype, schema = pick_json_content(rb.get("content", {}))
    if ctype is None:
        return None
    return {
        "required": bool(rb.get("required", False)),
        "contentType": ctype,
        "schema": schema if isinstance(schema, dict) else {},
    }


def response_sort_key(status: str) -> tuple[int, int]:
    """2xx first (ascending), then other numeric statuses (ascending), 'default' last."""
    if status == "default":
        return (3, 0)
    try:
        code = int(status)
    except ValueError:
        return (2, 0)
    bucket = 0 if 200 <= code < 300 else 1
    return (bucket, code)


def build_responses(spec: dict[str, Any], op: dict[str, Any]) -> list[dict[str, Any]]:
    responses: list[dict[str, Any]] = []
    for status, entry in (op.get("responses") or {}).items():
        resp = resolve_local_ref(spec, entry)
        if not isinstance(resp, dict):
            continue
        out: dict[str, Any] = {"status": str(status)}
        if isinstance(resp.get("description"), str):
            out["description"] = resp["description"]
        ctype, schema = pick_json_content(resp.get("content", {}))
        if ctype is not None:
            out["contentType"] = ctype
            if isinstance(schema, dict):
                out["schema"] = schema
        responses.append(out)
    responses.sort(key=lambda r: response_sort_key(r["status"]))
    return responses


def resource_base(path: str) -> str:
    base = ITEM_TAIL_RE.sub("", path)
    return base or path


def synth_description(method: str, path: str, params: list[dict[str, Any]]) -> str:
    """A one-line description for the ~94% of ops that carry only a summary. Done
    HERE (the deterministic projector), not in the UI, and phrased to read with the
    raw (often plural) table noun."""
    segments = [s for s in path.split("/") if s and not s.startswith("{")]
    noun = segments[-1] if segments else "resource"
    path_names = [p["name"] for p in params if p.get("in") == "path"]
    by = f" by {', '.join(path_names)}" if path_names else ""
    if method == "GET":
        return f"Fetch a record from {noun}{by}." if path_names else f"List {noun}."
    if method == "POST":
        return f"Create a record in {noun}."
    if method == "PUT":
        return f"Replace a record in {noun}{by}."
    if method == "PATCH":
        return f"Update fields of a record in {noun}{by}."
    if method == "DELETE":
        return f"Delete a record from {noun}{by}."
    return f"{method} {path}"


def collect_operations(spec: dict[str, Any]) -> list[dict[str, Any]]:
    paths: dict[str, Any] = spec.get("paths", {})
    top_security = spec.get("security")

    metas: list[dict[str, Any]] = []
    for path, path_item in paths.items():
        if not isinstance(path_item, dict):
            continue
        for method in METHODS:
            op = path_item.get(method)
            if not isinstance(op, dict):
                continue
            meta: dict[str, Any] = {
                "key": f"{method.upper()} {path}",
                "method": method.upper(),
                "path": path,
            }
            tags = op.get("tags")
            if isinstance(tags, list) and tags:
                meta["tag"] = tags[0]
            if isinstance(op.get("summary"), str):
                meta["summary"] = op["summary"]
            meta["params"] = build_params(spec, path_item, op)
            op_desc = op.get("description")
            meta["description"] = (
                op_desc.strip()
                if isinstance(op_desc, str) and op_desc.strip()
                else synth_description(method.upper(), path, meta["params"])
            )
            request_body = build_request_body(spec, op)
            if request_body is not None:
                meta["requestBody"] = request_body
            meta["responses"] = build_responses(spec, op)
            security = security_scheme_names(
                op["security"] if "security" in op else top_security
            )
            if security:
                meta["security"] = security
            metas.append(meta)

    # Family: group by collapsed resource base, then attach each group's sorted keys.
    groups: dict[str, list[str]] = {}
    for meta in metas:
        groups.setdefault(resource_base(meta["path"]), []).append(meta["key"])
    for keys in groups.values():
        keys.sort()
    for meta in metas:
        meta["family"] = groups[resource_base(meta["path"])]

    metas.sort(key=lambda m: m["key"])
    return metas


def emit_map(entries: dict[str, Any]) -> str:
    """One entry per line, value compact — like crud's table-metadata: small file,
    line-granular diffs. Keys and inner dict order are preserved by the caller
    (endpoint keys pre-sorted; schema/property order faithful to the spec)."""
    lines = ["{"]
    for key, value in entries.items():
        lines.append(f"  {json.dumps(key, ensure_ascii=False)}: {json.dumps(value, ensure_ascii=False)},")
    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    spec = json.loads(resolve_spec().read_text(encoding="utf-8"))
    schemas = spec.get("components", {}).get("schemas", {})
    if not isinstance(schemas, dict) or not schemas:
        raise SystemExit("no components.schemas found — spec layout changed?")

    metas = collect_operations(spec)
    if not metas:
        raise SystemExit("no operations found — spec layout changed?")

    # Insertion order == sorted key order (determinism); inner dict order is
    # preserved from the spec (no sort_keys) so schema property order is faithful.
    endpoints_map = {meta["key"]: meta for meta in metas}

    body = (
        HEADER
        + f"export const API_SCHEMAS: ApiSchemas = {emit_map(schemas)}\n\n"
        + f"export const API_ENDPOINTS: Record<string, EndpointMeta> = {emit_map(endpoints_map)}\n"
    )
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(body, encoding="utf-8")
    print(
        f"wrote {OUT_PATH.relative_to(TOOLKIT_PACKAGES)}: "
        f"{len(metas)} operations, {len(schemas)} schemas"
    )


if __name__ == "__main__":
    main()
