#!/usr/bin/env python3
"""Generate @agentic-toolkit/api-explorer's src/generated/endpoints.generated.ts.

The dumped spec (frontend/websites/adh/api/openapi.json) is the single authoritative
description of every REST endpoint — URL, params, request/response schemas, error
codes, tags, and (via collection + item path pairs) CRUD families. This script
projects it into a compact runtime module the ApiEndpointPanel consumes:

  * API_SCHEMAS   — the spec's components.schemas, verbatim. Stored ONCE; the panel
                    resolves `$ref` against it at render time (with a cycle guard),
                    so shared/recursive schemas don't bloat the file.
  * API_ENDPOINTS — one EndpointMeta per operation, keyed "<METHOD> <path>", with
                    param / body / response schemas kept as `$ref`s where the spec
                    used them (no inlining).

Deterministic output (endpoint keys sorted; inner dict order preserved from the
spec) so reruns are diff-stable; the drift gate (src/__tests__/endpoints.test.ts)
cross-checks the committed module against the spec.

Generic-CRUD operations carry no operationId, so operations are identified by
method+path only — which is exactly the map key.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from _spec_input import resolve_spec
from _stable_output import keeping_mtime_if_unchanged

PACKAGE_DIR = Path(__file__).resolve().parents[1]
#  This package now lives INSIDE agentictoolkit, so the package it writes into
#  (@agentic-toolkit/api-explorer, which owns the runtime half) is a sibling.
#  No repo-crossing walk any more.
TOOLKIT_PACKAGES = PACKAGE_DIR.parent
OUT_PATH = (
    TOOLKIT_PACKAGES / "api-explorer" / "src" / "generated" / "endpoints.generated.ts"
)

# Verbs we project. HEAD/OPTIONS/TRACE carry no try-it value.
METHODS = ("get", "post", "put", "patch", "delete")

# Strip exactly one trailing `/{param}` segment to collapse an item path onto its
# collection base, so `/x/y` and `/x/y/{id}` group together as one CRUD family.
ITEM_TAIL_RE = re.compile(r"/\{[^}]+\}$")


def _segments(path: str) -> list[str]:
    return [s for s in path.split("/") if s]


def _is_param(segment: str) -> bool:
    return segment.startswith("{") and segment.endswith("}")


def has_item_child(path: str, all_paths: dict[str, Any]) -> bool:
    """True when some other spec path extends `path` with a further `/{param}`
    — i.e. an individual item under it can be addressed by id. A genuine nested
    collection (`/x/{id}/tokens`, paired with `/x/{id}/tokens/{tokenId}`) has
    one; a one-shot action verb (`/x/{id}/restore`) never does. This is the
    load-bearing check in `is_action_subroute` below: without it, that
    predicate would also catch real sub-collections whose URL shape happens to
    match (final literal segment right after a `{param}`)."""
    prefix = path + "/{"
    return any(p.startswith(prefix) for p in all_paths if p != path)


def is_action_subroute(path: str, all_paths: dict[str, Any]) -> bool:
    """An ACTION SUB-ROUTE is a verb performed on an already-identified resource,
    not a table/collection of its own — e.g. `/organizations/{id}/restore` or
    `/access/items/restore`. `synth_description` and `resource_base` both need
    to recognise one: the former because none of its templates ("Create a
    record in X") makes sense when X is a verb, not a noun; the latter because
    such a path should family with the resource it acts on, not stand alone.

    Structural, not a hardcoded verb list — a path qualifies when its final
    segment is a literal (not a `{param}`), it has no item-child of its own
    (see `has_item_child` — nothing can be addressed *within* it by id, which
    is what would make it a real collection instead), and its prefix already
    names a real resource: either one specific item (the segment right before
    it is a `{param}`, e.g. `.../{id}/restore`) or a whole collection
    addressed by exactly `/{schema}/{table}` with no id at all (e.g.
    `/access/items/restore` — there is no per-item `/access/items/{id}` to
    act on instead). Checked by hand against the current spec: every path
    this matches — restore, rotate-token, publish, accept, connect, verify,
    and so on — really is a verb, never a table name a CRUD sentence could
    honestly describe.
    """
    segments = _segments(path)
    if not segments or _is_param(segments[-1]):
        return False
    if has_item_child(path, all_paths):
        return False
    prefix = segments[:-1]
    if not prefix:
        return False
    if _is_param(prefix[-1]):
        return True  # acts on one identified item: .../{id}/verb
    return len(prefix) == 2 and not any(_is_param(s) for s in prefix)  # /{schema}/{table}/verb

HEADER = """\
// GENERATED by @agentic-toolkit/adh-api-types tools/gen_endpoints.py — do not edit
// by hand. Source: adh's frontend/websites/adh/api/openapi.json, which is NOT in this
// repo — the spec is an explicit input, so regenerate with a path to an adh checkout:
//   pnpm --filter @agentic-toolkit/adh-api-types gen:api-endpoints -- <adh>/frontend/websites/adh/api/openapi.json
import type { ApiSchemas, EndpointMeta } from '../types'

"""


def resolve_local_ref(spec: dict[str, Any], node: Any) -> Any:
    """One-hop resolve of a `#/...` ref (params / requestBodies / responses live
    in components and may be referenced). Schema `$ref`s are deliberately LEFT in
    place — the panel resolves those against API_SCHEMAS."""
    if isinstance(node, dict) and "$ref" in node and isinstance(node["$ref"], str):
        ref = node["$ref"]
        if ref.startswith("#/"):
            target: Any = spec
            for part in ref[2:].split("/"):
                if not isinstance(target, dict) or part not in target:
                    return node
                target = target[part]
            return target
    return node


def pick_json_content(content: dict[str, Any]) -> tuple[str | None, Any]:
    """Prefer application/json; else the first declared content type."""
    if not isinstance(content, dict) or not content:
        return None, None
    if "application/json" in content:
        return "application/json", content["application/json"].get("schema")
    ctype = next(iter(content))
    entry = content.get(ctype) or {}
    return ctype, entry.get("schema") if isinstance(entry, dict) else None


def security_scheme_names(security: Any) -> list[str]:
    """Flatten OpenAPI `security` ([{scheme: scopes}, ...]) to sorted scheme names."""
    names: set[str] = set()
    if isinstance(security, list):
        for requirement in security:
            if isinstance(requirement, dict):
                names.update(requirement.keys())
    return sorted(names)


def build_params(spec: dict[str, Any], path_item: dict[str, Any], op: dict[str, Any]) -> list[dict[str, Any]]:
    # Path-level first so path params keep their leading position; an op-level entry
    # for the same (name, in) OVERRIDES the path-level one (OpenAPI's rule) while
    # keeping the slot — dict reassignment updates the value but not the position.
    raw = list(path_item.get("parameters", []) or []) + list(op.get("parameters", []) or [])
    merged: dict[tuple[str, str], dict[str, Any]] = {}
    for entry in raw:
        param = resolve_local_ref(spec, entry)
        if not isinstance(param, dict):
            continue
        location = param.get("in")
        name = param.get("name")
        if location not in ("path", "query") or not isinstance(name, str):
            continue
        out: dict[str, Any] = {
            "name": name,
            "in": location,
            # Path params are required by definition; honour explicit `required` otherwise.
            "required": True if location == "path" else bool(param.get("required", False)),
            "schema": param.get("schema", {}) if isinstance(param.get("schema"), dict) else {},
        }
        if isinstance(param.get("description"), str):
            out["description"] = param["description"]
        merged[(name, location)] = out
    return list(merged.values())


def build_request_body(spec: dict[str, Any], op: dict[str, Any]) -> dict[str, Any] | None:
    rb = resolve_local_ref(spec, op.get("requestBody"))
    if not isinstance(rb, dict):
        return None
    ctype, schema = pick_json_content(rb.get("content", {}))
    if ctype is None:
        return None
    return {
        "required": bool(rb.get("required", False)),
        "contentType": ctype,
        "schema": schema if isinstance(schema, dict) else {},
    }


def response_sort_key(status: str) -> tuple[int, int]:
    """2xx first (ascending), then other numeric statuses (ascending), 'default' last."""
    if status == "default":
        return (3, 0)
    try:
        code = int(status)
    except ValueError:
        return (2, 0)
    bucket = 0 if 200 <= code < 300 else 1
    return (bucket, code)


def build_responses(spec: dict[str, Any], op: dict[str, Any]) -> list[dict[str, Any]]:
    responses: list[dict[str, Any]] = []
    for status, entry in (op.get("responses") or {}).items():
        resp = resolve_local_ref(spec, entry)
        if not isinstance(resp, dict):
            continue
        out: dict[str, Any] = {"status": str(status)}
        if isinstance(resp.get("description"), str):
            out["description"] = resp["description"]
        ctype, schema = pick_json_content(resp.get("content", {}))
        if ctype is not None:
            out["contentType"] = ctype
            if isinstance(schema, dict):
                out["schema"] = schema
        responses.append(out)
    responses.sort(key=lambda r: response_sort_key(r["status"]))
    return responses


def resource_base(path: str, all_paths: dict[str, Any]) -> str:
    """Collapse a path onto the family it belongs to.

    An item path collapses onto its collection by stripping the trailing
    `/{param}` (`/x/y/{id}` -> `/x/y`), so a table's list/create and
    get/put/delete operations share one family — unchanged from before.

    An action sub-route (see `is_action_subroute`) collapses onto the SAME
    base as the resource it acts on, not onto itself: `/x/y/{id}/restore`
    strips both the trailing literal ("restore") and the `{param}` before it,
    landing on `/x/y` — exactly what `/x/y/{id}` resolves to. Without this,
    an action sub-route's family was itself alone (a singleton), so e.g. the
    explorer's "related calls" never linked an archive endpoint to its own
    restore. A collection-scoped action (no `{param}` to act on, e.g.
    `/access/items/restore`) has no item route to rejoin, so it only drops
    its own trailing literal segment.
    """
    base = ITEM_TAIL_RE.sub("", path)
    if base != path:
        return base or path
    if is_action_subroute(path, all_paths):
        segments = _segments(path)[:-1]
        if segments and _is_param(segments[-1]):
            segments = segments[:-1]
        base = "/" + "/".join(segments) if segments else path
    return base or path


def synth_description(
    method: str, path: str, params: list[dict[str, Any]], *, omit: bool
) -> str | None:
    """A one-line description for the ~94% of ops that carry only a summary. Done
    HERE (the deterministic projector), not in the UI, and phrased to read with the
    raw (often plural) table noun.

    `omit=True` means the caller has already decided this op's own summary
    should stand alone instead — see `collect_operations` for the two cases:
    an action sub-route (none of the templates below name a real table to
    describe) and a DELETE with a sibling `/restore` (the generic "Delete a
    record from X" phrasing is actively wrong, not just redundant, for a
    resource that is recoverable)."""
    if omit:
        return None
    segments = [s for s in path.split("/") if s and not s.startswith("{")]
    noun = segments[-1] if segments else "resource"
    path_names = [p["name"] for p in params if p.get("in") == "path"]
    by = f" by {', '.join(path_names)}" if path_names else ""
    if method == "GET":
        return f"Fetch a record from {noun}{by}." if path_names else f"List {noun}."
    if method == "POST":
        return f"Create a record in {noun}."
    if method == "PUT":
        return f"Replace a record in {noun}{by}."
    if method == "PATCH":
        return f"Update fields of a record in {noun}{by}."
    if method == "DELETE":
        return f"Delete a record from {noun}{by}."
    return f"{method} {path}"


def collect_operations(spec: dict[str, Any]) -> list[dict[str, Any]]:
    paths: dict[str, Any] = spec.get("paths", {})
    top_security = spec.get("security")

    # Family grouping only needs the path set (methods don't affect it), so
    # it's computed once, up front — both for each meta's own "family" field
    # and to decide, below, whether a DELETE has a sibling action sub-route
    # that makes the generic "Delete a record..." wording actively wrong
    # rather than merely synthesizable.
    bases: dict[str, str] = {
        path: resource_base(path, paths)
        for path, item in paths.items()
        if isinstance(item, dict)
    }
    groups: dict[str, list[str]] = {}
    for path, item in paths.items():
        if not isinstance(item, dict):
            continue
        for method in METHODS:
            if isinstance(item.get(method), dict):
                groups.setdefault(bases[path], []).append(f"{method.upper()} {path}")
    for keys in groups.values():
        keys.sort()

    # A DELETE on an item whose family also contains a `/restore` action isn't
    # really deleting the record — it's recoverable — so the generic "Delete a
    # record from X" template is actively false, not just redundant, whenever
    # the spec's own summary already says so (e.g. "Archive an organization").
    # Detected structurally, by the family (fixed above) having a sibling
    # action sub-route whose own final path segment is literally "restore" —
    # deliberately narrower than "any action sibling": most DELETE routes
    # have one (rotate-token, sync-status, ...) with no such contradiction,
    # and only a `restore` sibling specifically implies the delete doesn't
    # actually destroy anything.
    delete_families_with_restore = {
        base
        for base, keys in groups.items()
        if any(key.rsplit("/", 1)[-1] == "restore" for key in keys)
    }

    metas: list[dict[str, Any]] = []
    for path, path_item in paths.items():
        if not isinstance(path_item, dict):
            continue
        action_subroute = is_action_subroute(path, paths)
        for method in METHODS:
            op = path_item.get(method)
            if not isinstance(op, dict):
                continue
            meta: dict[str, Any] = {
                "key": f"{method.upper()} {path}",
                "method": method.upper(),
                "path": path,
            }
            tags = op.get("tags")
            if isinstance(tags, list) and tags:
                meta["tag"] = tags[0]
            has_summary = isinstance(op.get("summary"), str) and bool(op["summary"].strip())
            if isinstance(op.get("summary"), str):
                meta["summary"] = op["summary"]
            meta["params"] = build_params(spec, path_item, op)
            op_desc = op.get("description")
            omit = has_summary and (
                action_subroute
                or (method == "delete" and bases[path] in delete_families_with_restore)
            )
            if isinstance(op_desc, str) and op_desc.strip():
                meta["description"] = op_desc.strip()
            else:
                synthesized = synth_description(method.upper(), path, meta["params"], omit=omit)
                if synthesized is not None:
                    meta["description"] = synthesized
            request_body = build_request_body(spec, op)
            if request_body is not None:
                meta["requestBody"] = request_body
            meta["responses"] = build_responses(spec, op)
            security = security_scheme_names(
                op["security"] if "security" in op else top_security
            )
            if security:
                meta["security"] = security
            meta["family"] = groups[bases[path]]
            metas.append(meta)

    metas.sort(key=lambda m: m["key"])
    return metas


def emit_map(entries: dict[str, Any]) -> str:
    """One entry per line, value compact — like crud's table-metadata: small file,
    line-granular diffs. Keys and inner dict order are preserved by the caller
    (endpoint keys pre-sorted; schema/property order faithful to the spec)."""
    lines = ["{"]
    for key, value in entries.items():
        lines.append(f"  {json.dumps(key, ensure_ascii=False)}: {json.dumps(value, ensure_ascii=False)},")
    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    spec = json.loads(resolve_spec().read_text(encoding="utf-8"))
    schemas = spec.get("components", {}).get("schemas", {})
    if not isinstance(schemas, dict) or not schemas:
        raise SystemExit("no components.schemas found — spec layout changed?")

    metas = collect_operations(spec)
    if not metas:
        raise SystemExit("no operations found — spec layout changed?")

    # Insertion order == sorted key order (determinism); inner dict order is
    # preserved from the spec (no sort_keys) so schema property order is faithful.
    endpoints_map = {meta["key"]: meta for meta in metas}

    body = (
        HEADER
        + f"export const API_SCHEMAS: ApiSchemas = {emit_map(schemas)}\n\n"
        + f"export const API_ENDPOINTS: Record<string, EndpointMeta> = {emit_map(endpoints_map)}\n"
    )
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with keeping_mtime_if_unchanged(OUT_PATH):
        OUT_PATH.write_text(body, encoding="utf-8")
    print(
        f"wrote {OUT_PATH.relative_to(TOOLKIT_PACKAGES)}: "
        f"{len(metas)} operations, {len(schemas)} schemas"
    )


if __name__ == "__main__":
    main()
