import { defineConfig } from 'tsup'
import { preserveDirectivesPlugin } from 'esbuild-plugin-preserve-directives'

export default defineConfig({
  entry: {
    'appearance-mode-toggle/index': 'src/appearance-mode-toggle/index.ts',
    'appearance-mode-toggle/AppearanceModeToggle': 'src/appearance-mode-toggle/AppearanceModeToggle.tsx',
    'dev-banner/index': 'src/dev-banner/index.ts',
    'dev-banner/DevBanner': 'src/dev-banner/DevBanner.tsx',
    'filtered-list/index': 'src/filtered-list/index.ts',
    'filtered-list/FilteredList': 'src/filtered-list/FilteredList.tsx',
    'filtered-list/useFilteredList': 'src/filtered-list/useFilteredList.ts',
    'logging-panel/index': 'src/logging-panel/index.ts',
    'logging-panel/LogPanel': 'src/logging-panel/LogPanel.tsx',
    'orb-row/index': 'src/orb-row/index.ts',
    'orb-row/OrbRow': 'src/orb-row/OrbRow.tsx',
    'search-dialog/index': 'src/search-dialog/index.ts',
    'search-dialog/SearchDialog': 'src/search-dialog/SearchDialog.tsx',
    'search-dialog/SearchDialogConnected': 'src/search-dialog/SearchDialogConnected.tsx',
    'source-code-panel/index': 'src/source-code-panel/index.ts',
    'source-code-panel/SourceCodePanel': 'src/source-code-panel/SourceCodePanel.tsx',
    'source-code-panel/useSourceCode': 'src/source-code-panel/useSourceCode.ts',
    'source-code-panel/highlighter': 'src/source-code-panel/highlighter.ts',
    'user-settings/index': 'src/user-settings/index.ts',
    'user-settings/components/Checkbox': 'src/user-settings/components/Checkbox.tsx',
    'user-settings/components/ChoiceSlider': 'src/user-settings/components/ChoiceSlider.tsx',
    'user-settings/components/ColorPicker': 'src/user-settings/components/ColorPicker.tsx',
    'user-settings/components/Conditional': 'src/user-settings/components/Conditional.tsx',
    'user-settings/components/DismissibleHint': 'src/user-settings/components/DismissibleHint.tsx',
    'user-settings/components/Divider': 'src/user-settings/components/Divider.tsx',
    'user-settings/components/Explanation': 'src/user-settings/components/Explanation.tsx',
    'user-settings/components/Group': 'src/user-settings/components/Group.tsx',
    'user-settings/components/Header': 'src/user-settings/components/Header.tsx',
    'user-settings/components/Progress': 'src/user-settings/components/Progress.tsx',
    'user-settings/components/RadioGroup': 'src/user-settings/components/RadioGroup.tsx',
    'user-settings/components/Select': 'src/user-settings/components/Select.tsx',
    'user-settings/components/SettingsButton': 'src/user-settings/components/SettingsButton.tsx',
    'user-settings/components/SettingsPanel': 'src/user-settings/components/SettingsPanel.tsx',
    'user-settings/components/Slider': 'src/user-settings/components/Slider.tsx',
    'user-settings/components/Stack': 'src/user-settings/components/Stack.tsx',
    'user-settings/components/Stepper': 'src/user-settings/components/Stepper.tsx',
    'user-settings/components/TextField': 'src/user-settings/components/TextField.tsx',
    'user-settings/hooks/useSetting': 'src/user-settings/hooks/useSetting.ts',
  },
  outDir: 'dist',
  format: ['esm'],
  target: 'es2022',
  platform: 'browser',
  sourcemap: true,
  clean: true,
  dts: false,
  bundle: true,
  splitting: true,
  outExtension: () => ({ js: '.js' }),
  external: [
    'react',
    'react-dom',
    'react/jsx-runtime',
    '@agentic-web-toolkit/model',
    'shiki',
  ],
  esbuildPlugins: [
    preserveDirectivesPlugin({
      directives: ['use client', 'use server'],
      include: /\.(js|ts|jsx|tsx)$/,
      exclude: /node_modules/,
    }),
  ],
})
