// GENERATED FILE — do not edit by hand.
// Regenerate: python3 <websites-root>/tools/gen-site-routes.py --region main
//
// main's share of the fleet's page routes, derived from that repo's App Router
// trees. The rest is in its siblings `routes.marketing.generated.ts`, `routes.placeholder.generated.ts`, written by the other repos;
// `routes.generated.ts` merges them all and is what consumers import. See the
// generator's docstring for why this is one file per repo.
//
// `gen-site-routes.py --region main --check` re-derives this map in that
// repo's CI, so a page added, moved, or removed anywhere in its fleet fails there
// until the script is re-run.
//
// NOT dev-only tooling: research's `src/lib/sitemap-routes.ts` reads
// `SITE_ROUTES.research` at build time to derive which top-level and
// `[workspace]`-child segments are STATIC — i.e. which author or paper slugs would
// be shadowed by a real route — so research's public sitemap is a second,
// load-bearing consumer of this map, not just the flyout above. Do not prune
// either half for being unused outside dev tooling.
import type { SiteId } from './registry'

export const SITE_ROUTES_MAIN: Partial<Record<SiteId, readonly string[]>> = {
  admin: [
    '/',
    '/audit',
    '/auth/callback',
    '/authentication',
    '/feature-flags',
    '/feedback',
    '/invitations',
    '/llm-providers',
    '/login',
    '/messaging',
    '/privacy',
    '/reserved-identifiers',
    '/server-bags',
    '/sync',
    '/terms',
    '/usage',
    '/users',
  ],
  community: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/admin',
    '/admin/members',
    '/admin/topics',
    '/admin/topics/[id]',
    '/admin/topics/new',
    '/auth/callback',
    '/categories/[slug]',
    '/details',
    '/details/[topic]',
    '/discussions',
    '/discussions/[topicId]',
    '/discussions/new',
    '/forum',
    '/home',
    '/people',
    '/privacy',
    '/terms',
    '/topics/[slug]',
    '/tour',
  ],
  cookbook: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/appendix/[[...slug]]',
    '/auth/callback',
    '/compliance/[[...slug]]',
    '/guidelines/[[...slug]]',
    '/home',
    '/ingredients/[[...slug]]',
    '/introduction/[[...slug]]',
    '/principles/[[...slug]]',
    '/privacy',
    '/projects/[[...slug]]',
    '/recipes/[[...slug]]',
    '/reference/[[...slug]]',
    '/terms',
    '/tour',
  ],
  devteam: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/details/[[...path]]',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  docs: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  hub: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/academy/[[...path]]',
    '/[workspace]/all-data/[[...table]]',
    '/[workspace]/applications/[[...path]]',
    '/[workspace]/auth/[[...path]]',
    '/[workspace]/billing/[[...table]]',
    '/[workspace]/codereviews/[[...path]]',
    '/[workspace]/communities/[[...path]]',
    '/[workspace]/community/[[...path]]',
    '/[workspace]/consultants/[[...path]]',
    '/[workspace]/consulting/[[...path]]',
    '/[workspace]/cookbook/[[...path]]',
    '/[workspace]/customers/[[...path]]',
    '/[workspace]/dashboards/[[...topic]]',
    '/[workspace]/devices/[[...path]]',
    '/[workspace]/devteam/[[...path]]',
    '/[workspace]/docs/[[...path]]',
    '/[workspace]/domains/[[...path]]',
    '/[workspace]/education/[[...path]]',
    '/[workspace]/email-signup',
    '/[workspace]/feature-flags/[[...path]]',
    '/[workspace]/games/[[...path]]',
    '/[workspace]/gamification/[[...path]]',
    '/[workspace]/help/[[...path]]',
    '/[workspace]/integrations/[[...path]]',
    '/[workspace]/invitations/[[...path]]',
    '/[workspace]/knowledgebases/[[...table]]',
    '/[workspace]/llm-providers/[[...path]]',
    '/[workspace]/members',
    '/[workspace]/messaging/[[...rest]]',
    '/[workspace]/narratives/[[...rest]]',
    '/[workspace]/news/[[...path]]',
    '/[workspace]/notebook/[[...path]]',
    '/[workspace]/notifications/[[...path]]',
    '/[workspace]/orgs/[[...path]]',
    '/[workspace]/persona-services/[[...path]]',
    '/[workspace]/personabuilder/[[...path]]',
    '/[workspace]/personas/[[...path]]',
    '/[workspace]/products/[[...path]]',
    '/[workspace]/profile',
    '/[workspace]/projects/[[...path]]',
    '/[workspace]/recipes/[[...path]]',
    '/[workspace]/registries/[[...path]]',
    '/[workspace]/registry/[[...path]]',
    '/[workspace]/research/[[...path]]',
    '/[workspace]/server-bags/[[...path]]',
    '/[workspace]/settings/[[...path]]',
    '/[workspace]/signin-apps/[[...path]]',
    '/[workspace]/sites/[[...path]]',
    '/[workspace]/storage/[[...path]]',
    '/[workspace]/store/[[...path]]',
    '/[workspace]/stores/[[...path]]',
    '/[workspace]/support/[[...path]]',
    '/[workspace]/teambuilder/[[...path]]',
    '/[workspace]/teams/[[...path]]',
    '/[workspace]/testing/[[...path]]',
    '/[workspace]/tokens/[[...path]]',
    '/[workspace]/toolkit/[[...path]]',
    '/[workspace]/tools/[[...path]]',
    '/auth/callback',
    '/contact',
    '/details',
    '/details/[topic]',
    '/explore',
    '/features/[id]',
    '/home',
    '/integrations/oauth-callback',
    '/join',
    '/join/[eco]',
    '/join/verify',
    '/login',
    '/oidc/login',
    '/old-landing',
    '/privacy',
    '/settings/[[...topic]]',
    '/signup',
    '/terms',
    '/tour',
  ],
  'hub-help': [
    '/',
    '/[...slug]',
    '/auth/callback',
    '/chat',
    '/home',
    '/privacy',
    '/rest-api',
    '/rest-api/[...slug]',
    '/terms',
  ],
  personaregistry: [
    '/',
    '/[slug]',
    '/[slug]/[persona]',
    '/auth/callback',
    '/privacy',
    '/terms',
    '/tour',
  ],
  registry: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  research: [
    '/',
    '/[workspace]',
    '/[workspace]/[paperSlug]',
    '/[workspace]/edit/[paperUuid]',
    '/[workspace]/home/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/search',
    '/terms',
    '/tour',
  ],
  status: [
    '/',
    '/privacy',
    '/terms',
  ],
  toolkit: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/demo',
    '/demo/chat',
    '/demo/theme',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
}
