// GENERATED FILE — do not edit by hand.
// Regenerate: python3 <websites-root>/tools/gen-site-routes.py --region marketing
//
// marketing's share of the fleet's page routes, derived from that repo's App Router
// trees. The rest is in its siblings `routes.community.generated.ts`, `routes.cookbook.generated.ts`, `routes.devteam.generated.ts`, `routes.docs.generated.ts`, `routes.hub.generated.ts`, `routes.main.generated.ts`, `routes.personaregistry.generated.ts`, `routes.placeholder.generated.ts`, `routes.registry.generated.ts`, `routes.research.generated.ts`, `routes.shipr.generated.ts`, `routes.toolkit.generated.ts`, written by the other repos;
// `routes.generated.ts` merges them all and is what consumers import. See the
// generator's docstring for why this is one file per repo.
//
// `gen-site-routes.py --region marketing --check` re-derives this map in that
// repo's CI, so a page added, moved, or removed anywhere in its fleet fails there
// until the script is re-run.
//
// NOT dev-only tooling: research's `src/lib/sitemap-routes.ts` reads
// `SITE_ROUTES.research` at build time to derive which top-level and
// `[workspace]`-child segments are STATIC — i.e. which author or paper slugs would
// be shadowed by a real route — so research's public sitemap is a second,
// load-bearing consumer of this map, not just the flyout above. Do not prune
// either half for being unused outside dev tooling.
import type { SiteId } from './registry'

export const SITE_ROUTES_MARKETING: Partial<Record<SiteId, readonly string[]>> = {
  authentication: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  billing: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/claim',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  codereviews: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  communities: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  customers: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  dashboards: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  devices: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  domains: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  ecosystems: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  education: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  games: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  gamification: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  integrations: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/home',
    '/integrations/oauth-callback',
    '/privacy',
    '/terms',
    '/tour',
  ],
  knowledgebases: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  messages: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  messaging: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  narratives: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  notebook: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  notifications: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  orgs: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  personabuilder: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  personas: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  products: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  projects: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  recipes: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  registries: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/registry/[registry]',
    '/registry/[registry]/[entry]',
    '/search',
    '/terms',
    '/tour',
  ],
  sites: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  storage: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  stores: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  teambuilder: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
  testing: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/profile',
    '/auth/callback',
    '/home',
    '/privacy',
    '/terms',
    '/tour',
  ],
}
