// GENERATED FILE — do not edit by hand.
// Regenerate: python3 frontend/tools/gen-site-routes.py
//
// Every page route of every family site (main/ + marketing/), derived from each
// site's App Router tree. Lazy-loaded by the site menu (as the package subpath
// `@agentic-toolkit/adh-registry/routes`) to fill the dev "Routes" flyout for sites that
// pass no curated `routes` prop. A drift-guard test (siteRoutes.test.ts)
// re-derives this map from the filesystem, so a moved/added/removed page fails
// CI until the script is re-run.
import type { SiteId } from './registry'

export const SITE_ROUTES: Partial<Record<SiteId, readonly string[]>> = {
  academy: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
  ],
  admin: [
    '/',
    '/audit',
    '/auth/callback',
    '/authentication',
    '/feature-flags',
    '/feedback',
    '/invitations',
    '/llm-providers',
    '/login',
    '/messaging',
    '/privacy',
    '/server-bags',
    '/sync',
    '/terms',
    '/usage',
    '/users',
  ],
  authentication: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
  ],
  billing: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
  ],
  bitbag: [
    '/',
    '/privacy',
    '/terms',
  ],
  codereviews: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
  ],
  communities: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
  ],
  community: [
    '/',
    '/admin',
    '/admin/members',
    '/admin/topics',
    '/admin/topics/[id]',
    '/admin/topics/new',
    '/auth/callback',
    '/categories/[slug]',
    '/details',
    '/details/[topic]',
    '/discussions',
    '/discussions/[topicId]',
    '/discussions/new',
    '/home',
    '/people',
    '/privacy',
    '/terms',
    '/topics/[slug]',
  ],
  consultants: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
  ],
  consulting: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
  ],
  cookbook: [
    '/[[...slug]]',
    '/auth/callback',
    '/home',
    '/privacy',
    '/terms',
  ],
  customers: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
  ],
  dashboards: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home/[[...path]]',
    '/privacy',
    '/terms',
  ],
  devices: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
  ],
  devteam: [
    '/',
    '/auth/callback',
    '/home',
    '/privacy',
    '/terms',
  ],
  domains: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
  ],
  ecosystems: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home/[[...path]]',
    '/privacy',
    '/terms',
  ],
  education: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
  ],
  help: [
    '/',
    '/auth/callback',
    '/privacy',
    '/terms',
  ],
  hub: [
    '/',
    '/[slug]',
    '/[slug]/all-data/[[...table]]',
    '/[slug]/applications/[[...path]]',
    '/[slug]/auth/[[...path]]',
    '/[slug]/billing/[[...table]]',
    '/[slug]/communities/[[...table]]',
    '/[slug]/dashboards/[[...topic]]',
    '/[slug]/feature-flags/[[...path]]',
    '/[slug]/gamification/[[...path]]',
    '/[slug]/home',
    '/[slug]/integrations/[[...path]]',
    '/[slug]/invitations/[[...path]]',
    '/[slug]/knowledgebases/[[...table]]',
    '/[slug]/llm-providers/[[...path]]',
    '/[slug]/members',
    '/[slug]/messaging/[[...rest]]',
    '/[slug]/narratives/[[...rest]]',
    '/[slug]/persona-services/[[...path]]',
    '/[slug]/personas/[[...path]]',
    '/[slug]/products/[[...path]]',
    '/[slug]/projects/[[...path]]',
    '/[slug]/research/[[...path]]',
    '/[slug]/server-bags/[[...path]]',
    '/[slug]/settings/[[...path]]',
    '/[slug]/signin-apps/[[...path]]',
    '/[slug]/storage/[[...path]]',
    '/[slug]/teams/[[...path]]',
    '/[slug]/tokens/[[...path]]',
    '/auth/callback',
    '/contact',
    '/details',
    '/details/[topic]',
    '/home',
    '/home/settings/[[...topic]]',
    '/integrations/oauth-callback',
    '/join',
    '/join/[eco]',
    '/join/verify',
    '/login',
    '/oidc/login',
    '/old-landing',
    '/privacy',
    '/signup',
    '/terms',
  ],
  'hub-help': [
    '/',
    '/[...slug]',
    '/auth/callback',
    '/chat',
    '/home',
    '/privacy',
    '/rest-api',
    '/rest-api/[...slug]',
    '/terms',
  ],
  knowledgebases: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home/[[...path]]',
    '/privacy',
    '/terms',
  ],
  learntruefacts: [
    '/',
    '/auth/callback',
  ],
  myagenticteams: [
    '/',
    '/auth/callback',
    '/home',
    '/privacy',
    '/terms',
  ],
  narratives: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home/[[...path]]',
    '/privacy',
    '/terms',
  ],
  news: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/old-landing',
    '/privacy',
    '/terms',
  ],
  notifications: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
  ],
  personabuilder: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home/[[...path]]',
    '/privacy',
    '/terms',
  ],
  personaregistry: [
    '/',
    '/[slug]',
    '/[slug]/[persona]',
    '/[slug]/settings',
    '/auth/callback',
    '/home',
    '/org/[slug]',
    '/privacy',
    '/terms',
  ],
  personas: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
  ],
  products: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
  ],
  projects: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home/[[...path]]',
    '/privacy',
    '/terms',
  ],
  recipes: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
  ],
  registries: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
  ],
  research: [
    '/',
    '/[userSlug]',
    '/[userSlug]/[paperRoute]',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home/[[...path]]',
    '/privacy',
    '/search',
    '/terms',
  ],
  sites: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
  ],
  status: [
    '/',
    '/privacy',
    '/terms',
  ],
  storage: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
  ],
  support: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/old-landing',
    '/privacy',
    '/terms',
  ],
  teambuilder: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
  ],
  teamregistry: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home/[[...path]]',
    '/privacy',
    '/terms',
  ],
  toolkit: [
    '/',
    '/auth/callback',
    '/demo',
    '/demo/chat',
    '/demo/theme',
    '/home',
    '/privacy',
    '/terms',
  ],
  tools: [
    '/',
    '/auth/callback',
    '/details',
    '/details/[topic]',
    '/home',
    '/privacy',
    '/terms',
  ],
}
